server:
  port: 8081 # 客户端的端口没有要求
spring:
  application:
    name: eureka-client-b

# 注册的含义，就是将自己的信息（ip，端口等）发送至服务端（指定一个地址）

eureka:
  client:
    service-url: # 指定注册地址
      deafultZone: http://loacalhost:8761/eureka