server:
  port: 80 # 网关一般是80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true # 只要加了依赖 默认开启
      routes:
        - id: login-service-route  # 路由id 保持唯一即可
          uri: http://localhost:8081 # uri 同一资源定位符 url 同一资源标识符
          predicates:
            - Path=/doLogin  # 匹配规则 只要path匹配上了/doLogin 就往uri 转发，并且将路径带上